# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

# pod 'Leanplum-iOS-SDK'
pod 'LeanplumSegment', '~> 1.0.1'

target 'ticTacToeSwift' do




end

target 'ticTacToeSwiftTests' do

end

